import { Translations } from "./types";

export const en: Translations = {
  home: {
    heroLine1: "code, design and ",
    heroLine2: "performance.",
    subtitle: "Full Stack Developer & UI/UX Enthusiast",
    viewProjects: "View Projects",
    getInTouch: "Get in touch",
  },
  about: {
    headingPrefix: "About ",
    headingHighlight: "me",
    bioParagraphs: [
      "Hi! I'm Douglas, a Software Engineer with over 3 years of experience, specializing in full-stack development and modern web technologies. My journey spans from frontend to backend architecture, with a focus on building scalable, user-centered applications using React, Next.js, React Native, and TypeScript.",
      "My expertise includes comprehensive front-end development with HTML5, CSS3, JavaScript, and advanced React ecosystem, along with robust backend solutions. I've architected serverless infrastructures using AWS services such as Lambda, API Gateway, DynamoDB, S3, and SES, ensuring scalability and cost efficiency.",
      "Currently, I'm a Frontend Developer at Pepperlaw AI, where I led a complete UI restructuring of an AI-generated codebase, transforming it into a pixel-perfect, high-performance application. I developed a Word-like editor with Markdown support, comments, and multi-format export, and integrated WOPI (Web Application Open Platform Interface).",
      "I consistently apply best practices in SEO optimization, performance tuning (achieving 95+ Google PageSpeed scores), and code quality. My approach combines technical excellence with strategic thinking, always aiming to deliver innovative solutions that solve real-world problems using cutting-edge technologies and modern development methodologies.",
    ],
  },
  experience: {
    headingPrefix: "MY ",
    headingHighlight: "JOURNEY",
    subtitle: "Professional Experience, Education and Certifications",
    professionalTitle: "Professional Experience",
    educationTitle: "Education",
    certificationsTitle: "Courses and Certifications",
    jobs: [
      {
        role: "Fullstack Developer",
        company: "Pepperlaw AI",
        period: "Aug 2025 - Present",
        location: "Remote",
        description:
          "I joined a project with a front-end generated by Lovable's AI, completely disorganized and full of flaws. I needed to restructure the UI to align with the Design/UX team's design and make the product viable for corporate clients.",
        highlights: [
          "Led the UI restructuring using pixel-perfect React aligned with the Design/UX team's design, creating more maintainable components with improved performance, user experience, smooth and responsive navigation.",
          "Developed a Word-like editor with Markdown support, comments, and multi-format export, later integrating the system with WOPI (Web Application Open Platform Interface).",
          "This overhaul, done together with the development team, elevated product quality, reduced critical bugs, and directly contributed to winning the startup's first corporate client.",
        ],
        skills: ["React", "Markdown", "WOPI", "UI/UX", "Performance"],
      },
      {
        role: "Mid-Level Full Stack Developer",
        company: "C2A Soluções em Tecnologia",
        period: "Oct 2024 - Mar 2025",
        location: "Belém, Pará, Brazil",
        description:
          "I was responsible for the entire development cycle of an urban reports application in Belém do Pará, from requirements gathering to publishing on Android and iOS stores.",
        highlights: [
          "Developed the complete application using React Native and Expo, covering everything from requirements gathering to store publishing.",
          "Integrated Google Maps and Google Places APIs to enable real-time geolocation and rendering of reported points.",
          "Built the backend from scratch using serverless architecture with AWS Lambda, API Gateway, S3, DynamoDB, and SES, ensuring scalability and low operational cost.",
          "Delivered a complete, functional, and stable system that fully met client needs and went into production without incidents, being published on the Play Store.",
        ],
        skills: [
          "React Native",
          "Expo",
          "AWS Lambda",
          "DynamoDB",
          "Google Maps API",
          "API Gateway",
          "S3",
          "SES",
        ],
      },
      {
        role: "Mid-Level Back End Developer",
        company: "Avatech",
        period: "Apr 2024 - Mar 2025",
        location: "Remote",
        description:
          "I was hired as a freelancer to develop a complete serverless system from scratch, using Firebase Cloud Functions, Firestore, and Node.js.",
        highlights: [
          "Created an AI-powered quiz system based on LLMs, enabling automatic generation of personalized tests and intelligent grading according to business rules.",
          "Implemented an automatic scheduling system that adjusts test difficulty based on student performance.",
          "Integrated Stripe for subscription payments and dynamic links, delivering a solid and secure system with optimized checkout and high retention rate.",
        ],
        skills: [
          "Firebase",
          "Cloud Functions",
          "Firestore",
          "Node.js",
          "LLMs",
          "Stripe",
          "Serverless",
        ],
      },
      {
        role: "Full Stack Developer",
        company: "CASTA Tecnologia",
        period: "Aug 2022 - Jul 2024",
        location: "Belém, Pará, Brazil",
        description:
          "I worked on the development and maintenance of professional web projects, including complete website rebuilds, landing pages, and systems focused on performance, SEO, and user experience.",
        highlights: [
          "Implemented REST API integrations and SEO/speed optimizations (Google PageSpeed 95+), ensuring high performance and usability.",
          "Completely rebuilt a law firm website previously made in WordPress, migrating to Next.js with clean and scalable code.",
          "Was responsible for the redesign and development of the company's homepage with React and Tailwind CSS, creating a modern and strategic interface.",
          "Developed landing pages and web systems applying SEO best practices, version control with Git/GitHub, and agile methodologies (Scrum and Kanban).",
          "Created a complete website for a law firm with interactive interface and animations, highlighting user experience and brand value.",
        ],
        skills: [
          "React",
          "Next.js",
          "Tailwind CSS",
          "SEO",
          "REST APIs",
          "Git",
          "Scrum",
          "Kanban",
        ],
      },
    ],
    education: {
      degree: "Bachelor's in Computer Science",
      university: "UNAMA - University of the Amazon",
      location: "Belém, Pará, Brazil",
      period: "Feb 2022 - Dec 2025",
    },
    certifications: [
      {
        title: "Participation Certificate - Python Norte 2025",
        institution: "Even3",
        date: "Oct 2025",
      },
      {
        title: "Utilitarian Scrum",
        institution: "MindMaster Treinamentos",
        date: "Oct 2024",
      },
      {
        title: "Front-end from Scratch",
        institution: "Rocketseat",
        date: "Oct 2024",
      },
      {
        title: "Ubiquitous Week",
        institution: "UNAMA",
        date: "Jun 2024",
        tags: ["React", "REST API"],
      },
      {
        title: "Introduction to Front-End Development",
        institution: "Meta via Coursera",
        date: "May 2024",
        tags: ["CSS", "Bootstrap"],
      },
      {
        title: "Web Development: HTML, CSS, JS, React, TS",
        institution: "Udemy",
        date: "Apr 2024",
      },
      {
        title: "Scrum Fundamentals Certified (SFC)",
        institution: "SCRUMstudy - Accreditation Body",
        date: "Apr 2024",
      },
      {
        title: "Java Track",
        institution: "Rocketseat",
        date: "Mar 2024",
      },
      {
        title: "Working in a Digital World",
        institution: "IBM",
        date: "Mar 2024",
      },
      {
        title: 'Bootcamp "Hero Week"',
        institution: "Hero Code",
        date: "Feb 2024",
        tags: ["Next.js", "WebRTC"],
      },
      {
        title: "Web Pages with HTML5",
        institution: "DIO",
        date: "Aug 2023",
      },
      {
        title: "Logical Techniques for JavaScript",
        institution: "DIO",
        date: "Aug 2023",
      },
      {
        title: "Styling Pages with CSS",
        institution: "DIO",
        date: "Aug 2023",
      },
      {
        title: "Code Versioning with Git",
        institution: "DIO",
        date: "Aug 2023",
      },
      {
        title: "JavaScript",
        institution: "Curso em Vídeo",
        date: "Oct 2020",
      },
      {
        title: "DISCOVER",
        institution: "Rocketseat",
        date: "Jun 2020",
      },
    ],
  },
  projects: {
    heroLine1: "Creating Digital",
    heroLine2: "Solutions",
    heroHighlight: "Amazing",
    heroDescription:
      "Full stack developer passionate about transforming ideas into elegant and functional digital products. Specialized in modern technologies like React, Next.js, and TypeScript.",
    heroSubDescription:
      "Freelance projects built from scratch, crafted with dedication and attention to detail.",
    techHeadingPrefix: "TECHNOLOGIES ",
    techHeadingHighlight: "USED",
    techSubtitle:
      "Discover the tech stacks behind each project",
    statProjects: "Completed Projects",
    statTech: "Technologies and Tools",
    statYears: "Years of Experience",
    cards: [
      {
        title: "Moonbeam",
        description: "AI-assisted writing platform",
        stack: ["Next.js", "TypeScript", "OpenAI", "Tailwind CSS", "PostgreSQL"],
        category: "AI & Productivity",
      },
      {
        title: "Cursor",
        description: "Code editor with integrated AI",
        stack: ["React", "Electron", "Node.js", "AI Models", "Monaco Editor"],
        category: "Development Tools",
      },
      {
        title: "Rogue",
        description: "Project management system",
        stack: ["Vue.js", "Express", "MongoDB", "Socket.io", "Redis"],
        category: "Management",
      },
      {
        title: "Editorially",
        description: "Real-time collaborative editor",
        stack: ["React", "Slate.js", "WebSockets", "Node.js", "AWS"],
        category: "Collaboration",
      },
      {
        title: "Editrix AI",
        description: "AI-powered content editor",
        stack: ["Next.js", "GPT-4", "Supabase", "Vercel", "Tailwind CSS"],
        category: "AI & Editing",
      },
      {
        title: "Pixel Perfect",
        description: "Design tool for developers",
        stack: ["React", "Three.js", "WebGL", "TypeScript", "Framer Motion"],
        category: "Design & UI",
      },
      {
        title: "Algochurn",
        description: "Algorithm practice platform",
        stack: ["React", "Python", "FastAPI", "Docker", "PostgreSQL"],
        category: "Education",
      },
      {
        title: "Aceternity UI",
        description: "Modern component library",
        stack: [
          "React",
          "TypeScript",
          "Tailwind CSS",
          "Framer Motion",
          "Radix UI",
        ],
        category: "UI Library",
      },
      {
        title: "Tailwind Master Kit",
        description: "Complete Tailwind template kit",
        stack: ["HTML", "Tailwind CSS", "Alpine.js", "PostCSS", "Vite"],
        category: "Templates",
      },
    ],
  },
  meta: {
    title: "Douglas Oliveira | Full Stack Developer",
    description: "Douglas Oliveira's Portfolio",
  },
};
